In [1]:
from initial_plots import read_dataset
import numpy as np
from whole_pipeline import *
from utils_torch import *
import torch

KeyboardInterrupt: 

In [ ]:
df = read_dataset(gt=False)

X = np.array(df)
X = X.reshape((610,340, 103))

df = read_dataset(gt=True)
y = np.array(df)

rows_factor=31
cols_factor=31

#insert rows_overlap = -1 or cols_overlapp = -1 to avoid overlapping
rows_overlap=21
cols_overlap=21

"""
    cols overlap represents how many cols we precede before starting a new patch
    for example for a 1x9 grid with 1X3 patches and cols_overlap = 2:
    (1 2 [3) 4 (5] 6 [7) 8 9]
    similar to rows overlap

    idealy, to prevent data loss overlap should be 1
"""

'\n    cols overlap represents how many cols we precede before starting a new patch\n    for example for a 1x9 grid with 1X3 patches and cols_overlap = 2:\n    (1 2 [3) 4 (5] 6 [7) 8 9]\n    similar to rows overlap\n\n    idealy, to prevent data loss overlap should be 1\n'

In [ ]:
# old version- using whole X as data
# whole_pipeline_all(X,y, rows_factor, cols_factor, is_normalize_each_band=True, method_label_patch='center')

In [ ]:
# old version- using whole X as data
whole_pipeline_all_torch(torch.from_numpy(X),torch.from_numpy(y), rows_factor, cols_factor, rows_overlap, cols_overlap, is_normalize_each_band=True, method_label_patch='center')

XXXXXXX IN METHOD XXXXXXXXX
torch.Size([126])
PREPARE TIME:  1.7442798614501953
HDE TIME:  18.84658169746399
HDD TIME:  8.956784725189209
WHOLE METHOD TIME:  29.549675464630127
XXXXXXX IN CLASSIFICATION XXXXXXXXX
patch to points len:  126
DICT CREATION, SPLIT TETS TRAIN TIME:  0.0015444755554199219
patch_to_points_dict:  {5: (0, 20, 100, 120), 6: (0, 20, 120, 140), 8: (0, 20, 160, 180), 22: (20, 40, 100, 120), 24: (20, 40, 140, 160), 40: (40, 60, 120, 140), 41: (40, 60, 140, 160), 51: (60, 80, 0, 20), 53: (60, 80, 40, 60), 57: (60, 80, 120, 140), 68: (80, 100, 0, 20), 69: (80, 100, 20, 40), 72: (80, 100, 80, 100), 73: (80, 100, 100, 120), 76: (80, 100, 160, 180), 85: (100, 120, 0, 20), 86: (100, 120, 20, 40), 87: (100, 120, 40, 60), 88: (100, 120, 60, 80), 103: (120, 140, 20, 40), 122: (140, 160, 60, 80), 127: (140, 160, 160, 180), 128: (140, 160, 180, 200), 142: (160, 180, 120, 140), 154: (180, 200, 20, 40), 157: (180, 200, 80, 100), 160: (180, 200, 140, 160), 162: (180, 200, 180, 200

In [ ]:
# new version- dividing X to spectral bands
#whole_pipeline_divided(X,y, rows_factor, cols_factor, is_normalize_each_band=True, method_label_patch='center')



In [ ]:
# new version- dividing X to spectral bands
whole_pipeline_divided_torch(torch.from_numpy(X),torch.from_numpy(y), rows_factor, cols_factor, rows_overlap, cols_overlap, is_normalize_each_band=True, method_label_patch='center')



torch.Size([126])
PREPARE TIME:  1.2546260356903076
HDE TIME:  18.156456232070923
HDD TIME:  9.104510307312012
torch.Size([126])
PREPARE TIME:  1.314087152481079
HDE TIME:  18.01311993598938
HDD TIME:  9.285214185714722
torch.Size([126])
PREPARE TIME:  1.2116756439208984
HDE TIME:  10821.958170413971
HDD TIME:  22395.47429084778
torch.Size([126])
PREPARE TIME:  2.780723810195923
HDE TIME:  24.53837776184082
HDD TIME:  11.912703275680542
torch.Size([126])
PREPARE TIME:  1.1398015022277832
HDE TIME:  19.17076349258423
HDD TIME:  11.263040781021118
torch.Size([126])
PREPARE TIME:  1.4615256786346436
HDE TIME:  23.984838485717773
HDD TIME:  15.837554931640625
torch.Size([126])
PREPARE TIME:  2.2917463779449463
HDE TIME:  26.755918502807617
HDD TIME:  15.254922151565552
torch.Size([126])
PREPARE TIME:  1.840341329574585
HDE TIME:  33.38425588607788
HDD TIME:  15.570075511932373
torch.Size([126])
PREPARE TIME:  1.9374017715454102
HDE TIME:  30.223140716552734
HDD TIME:  14.902650356292725
to

In [ ]:
# #A test for overlapping patches:

# import torch
# from utils_torch import *

# def print_tensor(tensor):
#     for row in tensor:
#         print(' '.join([str(elem.item()).rjust(4) for elem in row]))

# rows = 5
# cols = 5
# data = torch.randint(0, 100, (rows, cols, 1), dtype=torch.int32)
# labels = torch.randint(0, 3, (rows, cols), dtype=torch.int32)
# print_tensor(labels)


# factor = 5
# overlap = 2
# patched_data, patched_labels, labels = patch_data_overlap_torch(data, labels, factor, factor, overlap, overlap, method_label_patch="center")

# print(patched_labels)


In [ ]:
# #A test for overlapping patches:

# import torch
# from utils_torch import *
# from classification import patch_to_points, point_to_patches, split_train_test

# def print_tensor(tensor):
#     for row in tensor:
#         print(' '.join([str(elem.item()).rjust(4) for elem in row]))

# rows = 3
# cols = 3
# data = torch.randint(0, 100, (rows, cols, 1), dtype=torch.int32)
# labels = torch.randint(0, 3, (rows, cols), dtype=torch.int32)
# print_tensor(labels)


# factor = 2
# overlap = 1
# patched_data, patched_labels, labels = patch_data_overlap_torch(data, labels, factor, factor, overlap, overlap)

# print("-----------------------")
# print_tensor(patched_labels)

# print("-----------------------")
# dictionary = (patch_to_points(patched_labels.flatten(), factor, factor, overlap, overlap, num_patches_in_row=patched_labels.shape[1]))
# print(dictionary)

# print("-----------------------")
# dictionary = point_to_patches(dictionary)
# print(dictionary)

# print("-----------------------")
# print(split_train_test(dictionary, patched_labels.flatten())[1])

# print("-----------------------")
# print(split_train_test(dictionary, patched_labels.flatten())[3])



In [ ]:
import torch

def remove_zeroes(tensor):
    non_zero_indices = tensor.nonzero()
    if non_zero_indices.numel() == 0:
        return tensor
    print(non_zero_indices)
    return tensor[non_zero_indices[:, 0], non_zero_indices[:, 1]]

# Create a tensor filled with integers from 0 to 2
tensor = torch.randint(0, 3, (4, 4))

print("Original Tensor:")
print(tensor)

# Remove zeroes from the tensor
tensor_without_zeroes = remove_zeroes(tensor)

print("\nTensor without Zeroes:")
print(tensor_without_zeroes)


Original Tensor:
tensor([[0, 2, 0, 2],
        [2, 0, 1, 0],
        [2, 1, 1, 0],
        [0, 1, 0, 0]])
tensor([[0, 1],
        [0, 3],
        [1, 0],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2],
        [3, 1]])

Tensor without Zeroes:
tensor([2, 2, 2, 1, 2, 1, 1, 1])
