In [1]:
from initial_plots import read_dataset
import numpy as np
from whole_pipeline import *
from utils_torch import *
import torch

device:  cuda


In [2]:
df = read_dataset(gt=False)

X = np.array(df)
X = X.reshape((610,340, 103))

df = read_dataset(gt=True)
y = np.array(df)

factor = 5
rows_factor = factor
cols_factor = factor

#insert rows_overlap = -1 or cols_overlapp = -1 to avoid overlapping
rows_overlap=21
cols_overlap=21

"""
    cols overlap represents how many cols we precede before starting a new patch
    for example for a 1x9 grid with 1X3 patches and cols_overlap = 2:
    (1 2 [3) 4 (5] 6 [7) 8 9]
    similar to rows overlap

    idealy, to prevent data loss overlap should be 1
"""

'\n    cols overlap represents how many cols we precede before starting a new patch\n    for example for a 1x9 grid with 1X3 patches and cols_overlap = 2:\n    (1 2 [3) 4 (5] 6 [7) 8 9]\n    similar to rows overlap\n\n    idealy, to prevent data loss overlap should be 1\n'

In [3]:
from utils_torch import validate_patches_generation
patches_sizes, validation_accs = validate_patches_generation(torch.from_numpy(X), torch.from_numpy(y), is_normalize_each_band=True, overlap_distance=factor, n_neighbors=3, checks=100)


PREPARE TIME:  10.720221519470215
HDE TIME:  128.1416437625885
HDD TIME:  0.0027267932891845703
DICT CREATION, THROW 0 LABELS, SPLIT TETS TRAIN TIME:  0.02704644203186035
patch_to_points_dict:  {0: (5, 11, 95, 101), 1: (5, 11, 100, 106), 2: (5, 11, 115, 121), 3: (5, 11, 130, 136), 4: (5, 11, 170, 176), 5: (5, 11, 175, 181), 6: (10, 16, 100, 106), 7: (10, 16, 110, 116), 8: (10, 16, 165, 171), 9: (10, 16, 170, 176), 10: (15, 21, 100, 106), 11: (15, 21, 105, 111), 12: (15, 21, 160, 166), 13: (15, 21, 165, 171), 14: (20, 26, 105, 111), 15: (20, 26, 110, 116), 16: (20, 26, 115, 121), 17: (20, 26, 155, 161), 18: (25, 31, 90, 96), 19: (25, 31, 95, 101), 20: (25, 31, 100, 106), 21: (25, 31, 105, 111), 22: (25, 31, 110, 116), 23: (25, 31, 115, 121), 24: (25, 31, 150, 156), 25: (25, 31, 155, 161), 26: (25, 31, 170, 176), 27: (30, 36, 75, 81), 28: (30, 36, 80, 86), 29: (30, 36, 110, 116), 30: (30, 36, 115, 121), 31: (30, 36, 145, 151), 32: (30, 36, 150, 156), 33: (35, 41, 70, 76), 34: (35, 41, 11

In [4]:
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('TkAgg')

plt.plot(patches_sizes, validation_accs)
plt.title('Validation of Patches Size with Center Labeling')
plt.xlabel('Patches Size')
plt.ylabel('Validation Accuracy')
plt.grid(True)
plt.show()

In [3]:
#best_patches_size = patches_sizes[np.argmax(validation_accs)]
best_patches_size = 6
#change:
# from classification import main
# #from classification_overlap import main
ks_1st_approach, validation_accs_1st_approach = validate_k(torch.from_numpy(X), torch.from_numpy(y), is_normalize_each_band=True, patches_size=best_patches_size, overlap_distance=factor, checks=100, method_label_patch='most_common')


RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

In [ ]:
#change:
# #from classification import main
# from classification_overlap import main
ks_2nd_approach, validation_accs_2nd_approach = validate_k(torch.from_numpy(X), torch.from_numpy(y), is_normalize_each_band=True, patches_size=best_patches_size, overlap_distance=factor, checks=100)


In [ ]:
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('TkAgg')

plt.plot(ks_1st_approach, validation_accs_1st_approach)
plt.plot(ks_2nd_approach, validation_accs_2nd_approach)
plt.title('Validation of k')
plt.xlabel('k')
plt.ylabel('Validation Accuracy')
plt.grid(True)
plt.show()

invalid command name "140207262177728delayed_destroy"
    while executing
"140207262177728delayed_destroy"
    ("after" script)
invalid command name "140207262363264delayed_destroy"
    while executing
"140207262363264delayed_destroy"
    ("after" script)
invalid command name "140208139949824delayed_destroy"
    while executing
"140208139949824delayed_destroy"
    ("after" script)
invalid command name "140208136981504delayed_destroy"
    while executing
"140208136981504delayed_destroy"
    ("after" script)
invalid command name "140208268307648delayed_destroy"
    while executing
"140208268307648delayed_destroy"
    ("after" script)
invalid command name "140208269005312delayed_destroy"
    while executing
"140208269005312delayed_destroy"
    ("after" script)


In [ ]:
# old version- using whole X as data
# whole_pipeline_all(X,y, rows_factor, cols_factor, is_normalize_each_band=True, method_label_patch='center')

In [ ]:
# old version- using whole X as data
whole_pipeline_all_torch(torch.from_numpy(X),torch.from_numpy(y), rows_factor, cols_factor, rows_overlap, cols_overlap, is_normalize_each_band=True, method_label_patch='center')

XXXXXXX IN METHOD XXXXXXXXX
PREPARE TIME:  1.0241162776947021
HDE TIME:  0.3664822578430176
HDD TIME:  0.31588125228881836
WHOLE METHOD TIME:  1.706479787826538
XXXXXXX IN CLASSIFICATION XXXXXXXXX
DICT CREATION, THROW 0 LABELS, SPLIT TETS TRAIN TIME:  0.0023763179779052734
patch_to_points_dict:  {0: (21, 42, 105, 126), 1: (42, 63, 21, 42), 2: (63, 84, 21, 42), 3: (63, 84, 42, 63), 4: (63, 84, 126, 147), 5: (84, 105, 21, 42), 6: (84, 105, 63, 84), 7: (84, 105, 84, 105), 8: (105, 126, 21, 42), 9: (105, 126, 42, 63), 10: (105, 126, 147, 168), 11: (126, 147, 0, 21), 12: (147, 168, 21, 42), 13: (147, 168, 42, 63), 14: (147, 168, 63, 84), 15: (147, 168, 105, 126), 16: (168, 189, 0, 21), 17: (168, 189, 105, 126), 18: (168, 189, 210, 231), 19: (189, 210, 84, 105), 20: (189, 210, 189, 210), 21: (231, 252, 42, 63), 22: (231, 252, 105, 126), 23: (231, 252, 147, 168), 24: (231, 252, 168, 189), 25: (273, 294, 84, 105), 26: (273, 294, 168, 189), 27: (273, 294, 189, 210), 28: (294, 315, 168, 189), 29

In [ ]:
# new version- dividing X to spectral bands
#whole_pipeline_divided(X,y, rows_factor, cols_factor, is_normalize_each_band=True, method_label_patch='center')



In [ ]:
# new version- dividing X to spectral bands
whole_pipeline_divided_torch(torch.from_numpy(X),torch.from_numpy(y), rows_factor, cols_factor, rows_overlap, cols_overlap, is_normalize_each_band=True, method_label_patch='center')



tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [ ]:
# #A test for overlapping patches:

# import torch
# from utils_torch import *

# def print_tensor(tensor):
#     for row in tensor:
#         print(' '.join([str(elem.item()).rjust(4) for elem in row]))

# rows = 5
# cols = 5
# data = torch.randint(0, 100, (rows, cols, 1), dtype=torch.int32)
# labels = torch.randint(0, 3, (rows, cols), dtype=torch.int32)
# print_tensor(labels)


# factor = 5
# overlap = 2
# patched_data, patched_labels, labels = patch_data_overlap_torch(data, labels, factor, factor, overlap, overlap, method_label_patch="center")

# print(patched_labels)


In [ ]:
# #A test for overlapping patches:

# import torch
# from utils_torch import *
# from classification import patch_to_points, point_to_patches, split_train_test

# def print_tensor(tensor):
#     for row in tensor:
#         print(' '.join([str(elem.item()).rjust(4) for elem in row]))

# rows = 3
# cols = 3
# data = torch.randint(0, 100, (rows, cols, 1), dtype=torch.int32)
# labels = torch.randint(0, 3, (rows, cols), dtype=torch.int32)
# print_tensor(labels)


# factor = 2
# overlap = 1
# patched_data, patched_labels, labels = patch_data_overlap_torch(data, labels, factor, factor, overlap, overlap)

# print("-----------------------")
# print_tensor(patched_labels)

# print("-----------------------")
# dictionary = (patch_to_points(patched_labels.flatten(), factor, factor, overlap, overlap, num_patches_in_row=patched_labels.shape[1]))
# print(dictionary)

# print("-----------------------")
# dictionary = point_to_patches(dictionary)
# print(dictionary)

# print("-----------------------")
# print(split_train_test(dictionary, patched_labels.flatten())[1])

# print("-----------------------")
# print(split_train_test(dictionary, patched_labels.flatten())[3])



In [ ]:
import torch

def remove_zeroes(tensor):
    non_zero_indices = tensor.nonzero()
    if non_zero_indices.numel() == 0:
        return tensor
    print(non_zero_indices)
    return tensor[non_zero_indices[:, 0], non_zero_indices[:, 1]]

# Create a tensor filled with integers from 0 to 2
tensor = torch.randint(0, 3, (4, 4))

print("Original Tensor:")
print(tensor)

# Remove zeroes from the tensor
tensor_without_zeroes = remove_zeroes(tensor)

print("\nTensor without Zeroes:")
print(tensor_without_zeroes)


Original Tensor:
tensor([[0, 2, 0, 2],
        [2, 0, 1, 0],
        [2, 1, 1, 0],
        [0, 1, 0, 0]])
tensor([[0, 1],
        [0, 3],
        [1, 0],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2],
        [3, 1]])

Tensor without Zeroes:
tensor([2, 2, 2, 1, 2, 1, 1, 1])
